description: Please reflect on the course this week and answer the following questions.
questions:
- text: You have just completed the final week of your Team project and are finalizing your research memo and summary slide.
    Professor Berry will have looked at all of the summary slides prior to our final lab meeting.
  type: essay
- text: What parts of the process (e.g., analysis, interpretation, communicating results) do you feel most confident in your
    ability to contribute to or do well?
  type: essay
- text: Considering those experiences, how did this project help build or challenge your confidence as an independent researcher
    as you prepare to move on to your next classes and future research opportunities?
  type: essay
