description: Please reflect on the course this week and answer the following questions.
questions:
- text: We are a little over halfway through the semester. How has the research process you experienced so far been similar
    to what you expected at the beginning of the semester?
  type: essay
- text: How has the research process you experienced so far been different to what you expected at the beginning of the semester?
  type: essay
