description: Please reflect on the course this week and answer the following questions.
questions:
- text: You have just completed your first week working on your team’s proposed project. Thinking about the feedback you have
    received and your first week of work, what do you think is the most important for your team to focus on or adjust as you
    move into Week 2?
  type: essay
- text: Explain your reasoning for this choice.
  type: essay
